nabito/rootfs/app/config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
    resources :transactions
    resources :connectors
    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    #root 'application#hello'
    root to: 'visitors#index'

    get 'connectors/:id/switch_on', to: 'connectors#switch_on', as: :switch_on_connector
    get 'connectors/:id/switch_off', to: 'connectors#switch_off', as: :switch_off_connector
    get 'connectors/:id/sync', to: 'connectors#sync', as: :sync_connector
  end

  #get 'users/:id/menu', to: 'users#menu', as: :menu_user
end

nabito/rootfs/app/app/models/connector.rb
# == Schema Information
#
# Table name: connectors
#
#  id                    :integer          not null, primary key
#  name                  :string
#  command_topic         :string
#  state_topic           :string
#  json_attributes_topic :string
#  payload_on            :string
#  payload_off           :string
#  state_on              :string
#  state_off             :string
#  power                 :decimal(, )
#  voltage               :integer
#  i_max                 :decimal(, )
#  price_per_kWh         :decimal(, )
#  frequency             :integer
#  state                 :string
#  current_user          :integer
#  current_tnx           :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  user_id               :integer
#  current_kWh           :decimal(, )
#  shadow_state          :string
#  json_state            :json
#  last_timestamp        :datetime
#

# Generic class for connectors - currently only Sonoff Pow2 implemented
class Connector < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :command_topic, presence: true
  validates :state_topic, presence: true
  validates :json_attributes_topic, presence: true
  validates :price_per_kWh, numericality: true

  enum state: { unknown: 'UNKNOWN', off: 'OFF', on: 'ON', error: 'ERROR' }

  after_initialize do
    if new_record?
      # default values for new record
      self.state = 'UNKNOWN'
      self.shadow_state = 'OFF'
      self.frequency = 60
      self.payload_on = 'ON'
      self.payload_off = 'OFF'
      self.state_on = 'ON'
      self.state_off = 'OFF'
      self.i_max = 16
      self.voltage = 230
    end
  end

  def in_use
    on?
  end

  def ping_topic
    'cmnd/' + name + '/teleperiod'
  end

  def switch_on(active_user, tag_id = nil)
    ConnectorRequestJob.perform_later(command_topic, payload_on)
    # TODO: tags later , tag_id_start: tag_id
    tnx = Transaction.create!(debtor_id: active_user.id, creditor_id: user_id,
                             connector_id: id,
                             average_price_per_kWh: price_per_kWh)

    tnx.save

    ConnectorRequestJob.perform_later(ping_topic, frequency)
    ConnectorSyncJob.perform_later(id)
    tnx.start

    update(shadow_state: :on, current_user: active_user.id,
           current_tnx: tnx.id)
  end

  def switch_off(active_user, tag_id = nil)
    ConnectorRequestJob.perform_later(command_topic, payload_off)
    ConnectorRequestJob.perform_later(ping_topic, frequency)
    ConnectorSyncJob.perform_later(id)
    tnx = Transaction.find(current_tnx)
    tnx.finish
    update(shadow_state: :off, current_user: nil, current_tnx: nil)
  end

  def mqtt_refresh_state()
    mq = MqttClient.new
    mq.send_message(ping_topic, frequency)
  end

  def mqtt_get_state()
    mq = MqttClient.new
    mqtt_state =  mq.get_message(json_attributes_topic)
    @json_state = JSON.parse(mqtt_state)
  end

  def state_energy_total
    mqtt_get_state()
    energy_total()
  end

  def energy_total
    return json_state['ENERGY']['Total'] if json_state
  end




  #tele/sonoff1/SENSOR 
  #{"Time":"2019-06-18T08:57:19","ENERGY":{"TotalStartTime":"2019-01-30T13:44:46","Total":38.854,"Yesterday":0.354,"Today":0.000,"Period":0,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}

  def sync_state()
    mqtt_get_state()
    ts_now = Time.now.utc
    puts "UTC time now: " + ts_now.to_s
    puts "connector time: " + @json_state["Time"] 
    last_ts = @json_state["Time"] + " +0000" #make sure its UTC timestamp
    ts1 = Time.parse(last_ts)
    if (ts_now - ts1) > 600
      update(state: :unknown)
    else  #connector is reachable, sync it's state with shadow
      update(state: shadow_state)
    end

  end

  def meter_values(iot_client)
      shadow = iot_client.get_thing_shadow({
        thing_name: box.aws_thing_name
      })
      o = JSON[shadow.payload.string]
      meter_values = o["state"]["reported"]["connectors"][name]["meter_values"]
      return meter_values 
  end





end

nabito/rootfs/app/app/controllers/connectors_controller.rb
class ConnectorsController < ApplicationController
  before_action :set_connector,
                only: %i[show edit update destroy switch_on switch_off sync]
  before_action :authenticate_user!

  def switch_on
    # return unless user_approved
    @connector.switch_on(current_user) if switch_on_check

    redirect_to @connector # notice: 'El socket was successfully created.' 
  end

  def switch_off
    # return unless user_approved
    @connector.switch_off(current_user) if switch_off_check

    redirect_to @connector
  end

  def sync
    if Time.now.utc - @connector.last_timestamp > 60.seconds
      ConnectorRequestJob.perform_later(@connector.ping_topic,
                                        @connector.frequency)
      ConnectorSyncJob.perform_later(@connector.id)
    end
    redirect_to @connector
  end

  # GET /connectors
  # GET /connectors.json
  def index
    @connectors = Connector.all
  end

  # GET /connectors/1
  # GET /connectors/1.json
  def show
    # @connector.mqtt_refresh_state()
    # @connector.sync_state()
    # MqttRequestJob.perform_later(@connector)

  end

  # GET /connectors/new
  def new
    @connector = Connector.new
  end

  # GET /connectors/1/edit
  def edit
  end

  # POST /connectors
  # POST /connectors.json
  def create
    @connector = Connector.new(connector_params)
    @connector.user_id = current_user.id

    respond_to do |format|
      if @connector.save
        format.html { redirect_to @connector, notice: 'Connector was successfully created.' }
        format.json { render :show, status: :created, location: @connector }
      else
        format.html { render :new }
        format.json { render json: @connector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /connectors/1
  # PATCH/PUT /connectors/1.json
  def update
    respond_to do |format|
      if @connector.update(connector_params)
        format.html { redirect_to @connector, notice: 'Connector was successfully updated.' }
        format.json { render :show, status: :ok, location: @connector }
      else
        format.html { render :edit }
        format.json { render json: @connector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /connectors/1
  # DELETE /connectors/1.json
  def destroy
    @connector.destroy
    respond_to do |format|
      format.html { redirect_to connectors_url, notice: 'Connector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_connector
    @connector = Connector.find(params[:id])
  end

  def switch_on_check
    if @connector.in_use
      if @connector.current_user == current_user.id
        flash[:notice] = 'Socket already switched on'
      else
        flash[:notice] = 'Socket currently used by a different user'
      end
      return false
    else
      flash[:notice] = 'Socket switched on'
      return true
    end
  end

  def switch_off_check
    if @connector.in_use
      if @connector.current_user == current_user.id
        flash[:notice] = 'Socket switched off'
        return true
      else
        flash[:notice] = 'Socket currently used by a different user'
        return false
      end
    else
      flash[:notice] = 'Socket is already off'
      return false
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def connector_params
    params.require(:connector).permit(:owner, :name, :command_topic, :state_topic, :json_attributes_topic, :payload_on, :payload_off, :state_on, :state_off, :power, :voltage, :i_max, :price_per_kWh, :frequency, :state, :current_user, :current_tnx)
  end
end

nabito/rootfs/app/app/helpers/connectors_helper.rb
module ConnectorsHelper
end

nabito/rootfs/app/app/views/connectors/_form.html.slim
= form_for @connector do |f|
  - if @connector.errors.any?
    #error_explanation
      h2 = "#{pluralize(@connector.errors.count, "error")} prohibited this connector from being saved:"
      ul
        - @connector.errors.full_messages.each do |message|
          li = message

  .row
    .col-md-6
      .row
        .col-md-8
          .form-group
            = f.label :name
            = f.text_field :name, class: "form-control"
        .col-md-4 
          .form-group
            label for="autofill_chbx" Autofill MQTT topics
            br 
            input#autofill_chbx type="checkbox" name="Autofill topics" checked="true"/
      .form-group
        = f.label :price_per_kWh
        = f.text_field :price_per_kWh, class: "form-control"
    .col-md-6
      .form-group
        = f.label :command_topic
        = f.text_field :command_topic, class: "form-control"
      .form-group
        = f.label :state_topic
        = f.text_field :state_topic, class: "form-control"
      .form-group
        = f.label :json_attributes_topic
        = f.text_field :json_attributes_topic, class: "form-control"

  .row
    .col-md-6
      a.btn.btn-secondary aria-controls="collapseExample" aria-expanded="false" data-toggle="collapse" href="#collapseExample" role="button" 
        | More details
  br
  #collapseExample.collapse.row
    .col-md-6
      .form-group
        = f.label :payload_on
        = f.text_field :payload_on, class: "form-control"
      .form-group
        = f.label :payload_off
        = f.text_field :payload_off, class: "form-control"
      .form-group
        = f.label :state_on
        = f.text_field :state_on, class: "form-control"
      .form-group
        = f.label :state_off
        = f.text_field :state_off, class: "form-control"
    .col-md-6
      .form-group
        = f.label :power, "Max Power (in kWhs)"
        = f.text_field :power, class: "form-control"
      .form-group
        = f.label :voltage
        = f.number_field :voltage, class: "form-control"
      .form-group
        = f.label :i_max
        = f.text_field :i_max, class: "form-control"
      .form-group
        = f.label :frequency
        = f.number_field :frequency, class: "form-control"
  .actions = f.submit class: "btn btn-primary"

nabito/rootfs/app/app/views/connectors/edit.html.slim
h1 Editing connector

== render 'form'

=> link_to 'Show', @connector
'|
=< link_to 'Back', connectors_path

nabito/rootfs/app/app/views/connectors/index.html.slim
h1 Listing connectors

br
.list-group
  - @connectors.each do |connector|
    a href=connector_path(connector) class="list-group-item list-group-item-action"
      .row
        .col-sm-3
          span = connector.user.email
        .col-sm-2
          span = "Status: " + connector.state.to_s
          br
          span = connector.power
        .col-sm-4
          span = connector.command_topic
          br  
          span = connector.state_topic
        .col-sm-3
          span = "Price per kWh: " + connector.price_per_kWh.to_s

br/
- if current_user.admin
  span = link_to 'New Connector', new_connector_path, class: ["btn", "btn-outline-primary", "btn-sm"]

/        td = link_to 'Show', connector
/        td = link_to 'Edit', edit_connector_path(connector)
/        td = link_to 'Destroy', connector, data: { confirm: 'Are you sure?' }, method: :delete

nabito/rootfs/app/app/views/connectors/new.html.slim
h1 New connector

== render 'form'

br
br
.text-right
  = link_to 'Back', connectors_path, class: "btn btn-light"

javascript:
  $("#connector_name").keyup(function() {
    if ($("#autofill_chbx").prop("checked")) {
      $("#connector_command_topic").val("cmnd/" + $("#connector_name").val() + "/power");
      $("#connector_state_topic").val("stat/" + $("#connector_name").val() + "/POWER");
      $("#connector_json_attributes_topic").val("tele/" + $("#connector_name").val() + "/SENSOR");
    }
  });

  $("#connector_name").change(function() {
    if ($("#autofill_chbx").prop("checked")) {
      $("#connector_command_topic").val("cmnd/" + $("#connector_name").val() + "/power");
      $("#connector_state_topic").val("stat/" + $("#connector_name").val() + "/POWER");
      $("#connector_json_attributes_topic").val("tele/" + $("#connector_name").val() + "/SENSOR");
    }
  });

nabito/rootfs/app/app/views/connectors/show.html.slim
.row
  .col-md-12.text-right
    /span = button_to "Refresh", "", { :onclick => "history.go(0)", :method => :get, class: ["btn-default"] } 
    br/
    = link_to "Sync", sync_connector_path(@connector), class: ["btn", "btn-primary", "btn-sm"]
    - if current_user.admin
        span = link_to t('.edit _connector'), edit_connector_path(@connector), class: ["btn", "btn-warning", "btn-sm"]

 
.row
  .col-md-12
    /p#notice = notice
    h1 = t('.Connector') + " ID: " + @connector.name
.row
  .col-md-12
    .table-responsive
          table.table.table-bordered.table-hover
            tbody
              tr
                th = "Status"
                td = @connector.state
              tr
                th = "Updated at"
                td = @connector.updated_at
              tr
                th = "JSON"
                td = @connector.json_state
.row
  .col-md-12
    .table-responsive
      table.table.table-bordered.table-hover.text-center
        tbody
          tr
            th = "Current power"
            td
              - if @connector.on?
                  strong =  @connector.power.to_s + " W"
              - else
                  strong = "0 Watts" 
          tr
            th = "Meter" 
            td = @connector.energy_total.to_s +  " kWh"
- if !@connector.unknown?                        
    .row  
      .col-md-6.text-center.col-xs-3
        = link_to "ON", switch_on_connector_path(@connector), class: ["btn", "btn-primary", "btn-lg"]
        |&nbsp;    
      .col-md-6.text-center.col-xs-3
        = link_to "OFF", switch_off_connector_path(@connector), class: ["btn", "btn-secondary", "btn-lg"]            
        |&nbsp;
    .row
      .col-md-12
        |&nbsp;
/ - if @connector.in_use                
/     .row
/       .col-md-12
/         h3 Current energy graph
/         = line_chart @connector.current_graph, xtitle: "Time", ytitle: "Watts", curve: false 
    
    
.row
  .col-md-12
    .table-responsive
          table.table.table-bordered.table-hover
            tbody
              tr
                th = "Command topic:"
                td = @connector.command_topic
              tr
                th = "State topic:"
                td = @connector.state_topic
              tr
                th = "JSON Attributes topic"
                td = @connector.json_attributes_topic
              tr
                th = "Max Power" 
                td = @connector.power
              tr
                th = "Voltage (V)"
                td = @connector.voltage
              tr 
                th = "max AC continuous (A)" 
                td = @connector.i_max
              tr
                th = "Price (per kWh):" 
                td = @connector.price_per_kWh
.row
  .col-md-12
    .table-responsive
          table.table.table-bordered.table-hover
            tbody    
              tr
                th = "Owner:" 
                td = @connector.user.email
              tr
                th = "Code:"
                td = @connector.name
              tr
                th = "Monitoring frequency:"
                td = @connector.frequency