nabito/rootfs/app/config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
    resources :transactions
    resources :connectors
    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    #root 'application#hello'
    root to: 'visitors#index'

    get 'connectors/:id/switch_on', to: 'connectors#switch_on', as: :switch_on_connector
    get 'connectors/:id/switch_off', to: 'connectors#switch_off', as: :switch_off_connector
    get 'connectors/:id/sync', to: 'connectors#sync', as: :sync_connector
  end

  #get 'users/:id/menu', to: 'users#menu', as: :menu_user
end

nabito/rootfs/app/app/views/layouts/_footer.html.slim
footer
  .row
    .col-lg-12
      p.text-center
        | Nabito 2019 | Systems Distributed

nabito/rootfs/app/app/views/layouts/_links_auth.html.slim
- if user_signed_in?
  / li.nav-item = link_to t('.menu'), menu_user_path(current_user), class: "nav-link"
  /li.nav-item = link_to t('.users'), users_path, class: "nav-link"
  li.nav-item = link_to t('.sign_out'), destroy_user_session_path, :method=>'delete', class: "nav-link"
- else
  li.nav-item = link_to t('.sign_in'), new_user_session_path, class: "nav-link"
  li.nav-item = link_to t('.sign_up'), new_user_registration_path, class: "nav-link"
li.nav-item = link_to t('.about'), "#about", class: "nav-link"
li.nav-item = link_to t('.contact'), "#contact", class: "nav-link"

nabito/rootfs/app/app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

nabito/rootfs/app/app/views/layouts/_navigation.html.slim
/ / navigation styled for Bootstrap 3.0
/ nav#mainNav.navbar.navbar-default.navbar-fixed-top
/   .container-fluid
/     .navbar-header
/       button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button" 
/         span.sr-only Toggle navigation
/         span.icon-bar
/         span.icon-bar
/         span.icon-bar
/       = link_to "NABITO - personal metering network", root_path, class: "navbar-brand nav-link"
/     #navbar.navbar-collapse.collapse
/       ul.nav.navbar-nav.navbar-right
/         == render 'layouts/links_auth'
/         li.dropdown.nav-item
/           a.dropdown-toggle.nav-link aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
/             = t('.lang.language')
/             span.caret
/           ul.dropdown-menu
/             li = link_to t('.lang.english'), locale: :en
/             li = link_to t('.lang.slovak'), locale: :sk
/         /    li = link_to t('.lang.czech'), locale: :cs
/         /    li = link_to t('.lang.german'), locale: :de
/         /    li = link_to t('.lang.polish'), locale: :pl


/      ul.nav.navbar-nav
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to "NABITO - mini-metering app", root_path, class: "navbar-brand"
  / a.navbar-brand[href="#"]
  /   | Nabito - the metering network
  button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"]
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item = link_to t('.connectors'), connectors_path, class: "nav-link"
      li.nav-item = link_to t('.transactions'), transactions_path, class: "nav-link"
      / li.nav-item = link_to t('.data'), connector_states_path, class: "nav-link"            
      / li.nav-item
      /   a.nav-link.disabled[href="#"]
      /     | Disabled
    ul.navbar-nav
      == render 'layouts/links_auth'
      li.nav-item.dropdown
        a#navbarDropdown.nav-link.dropdown-toggle[href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
          | Language
        .dropdown-menu[aria-labelledby="navbarDropdown"]
          = link_to t('.lang.english'), url_for( :locale => 'en' ), class: "dropdown-item"
          .dropdown-divider          
          = link_to t('.lang.slovak'), url_for( :locale => 'sk' ), class: "dropdown-item"          
    / form.form-inline.my-2.my-lg-0
    /   input.form-control.mr-sm-2[type="search" placeholder="Search" aria-label="Search"]
    /   button.btn.btn-outline-success.my-2.my-sm-0[type="submit"]
    /     | Search
    

nabito/rootfs/app/app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = content_for?(:title) ? yield(:title) : "My Application"
    |  <meta name="description" content="
    = content_for?(:description) ? yield(:description) : "My Application"
    | "> 
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body#page-top
    header
      .masthead2.text-center.text-white.d-flex
      == render 'layouts/navigation'
    main[role="main"]
      -if yield(:title)=='Home'
        == render 'layouts/messages'
        == yield
        == render 'layouts/footer'
      -else
        .container
          == render 'layouts/messages'
          == yield
          == render 'layouts/footer'